# Generated by Django 4.2.6 on 2023-10-26 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date_now',
            field=models.DateTimeField(null=True, verbose_name='Tarih - Saat'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appMy.post', verbose_name='Hangi posta ait'),
        ),
    ]
